stages:
  - deploy
  - publish

variables:
  DEPENDENCIES: findutils git libxslt python3-pip rubygem-jekyll yelp-tools

pages:
  stage: deploy
  image: fedora:33
  script:
    - dnf install -y $DEPENDENCIES
    - jekyll build -d public/
    - git checkout master
    - pip3 install pintail
    - cd help/C/
    - pintail build -o ../../public/help/
  artifacts:
    paths:
      - public
  only:
    - pages

cloudflareworkers:
  stage: publish
  image: node:12-alpine
  script:
    - npm install @cloudflare/wrangler
    - npx wrangler publish --env production
    - npx wrangler publish --env oldproduction
  only:
    - pages
