image: fedora:rawhide
stages:
  - check
  - build

variables:
  DEPENDENCIES: python3 pygobject3 gobject-introspection
                python3-gobject gtk3 gtksourceview3
                python3-pytest intltool

before_script:
  - dnf update -y
  - dnf install -y $DEPENDENCIES

flake8:
  stage: check
  script:
    - pip3 install -r dev-requirements.txt
    - flake8 bin/meld meld/
  allow_failure: true

pytest:
  stage: check
  script:
    - py.test-3 test/

build:
  stage: build
  script:
    - python3 setup.py build
