name = "meld-app"
account_id = "6339f2b9496297204382eca4fb01f7e2"
workers_dev = true
main = "workers-site/index.js"
compatibility_date = "2023-03-24"

[site]
bucket = "./public"

[env.production]
workers_dev = false
zone_id = "b64c0c8b024e2c6dd513e48a2b346d7b"
route = "meld.app/*"

[env.oldproduction]
workers_dev = false
zone_id = "a392a6a7338a2bf19fa1386a17e47a4f"
route = "meldmerge.org/*"
